### ISSUE TITLE
Check slides

### ISSUE THREAD

**Issue by robjhyndman** [rstudio-conf-2020/time-series-forecasting#2]
Please go through slides to check for errors, especially in R code.

**Comment by mitchelloharawild** [comment]
Some thoughts:
- [x] Introduce `facet_calendar()` instead of `frame_calendar()`.
- [x] `gather()`/`spread()` should become `pivot_*()` variants.
- [x] Gradually introduce inflation adjustment code - a full page of code can be daunting.
- [x] Potentially generalise transformation section beyond `box_cox()`. Perhaps `logp1()` is worth a mention?
- [x] Better to use `features()` with `ljung_box()` - that way it works for many series/models and gives a tibble in return.
- [x] lab session 18 requests piecewise linear trend, of which I do not recall being introduced yet.
- [x] reduce pdf size and loading times by using raster images.

**Comment by mitchelloharawild** [comment]
Checked, slides and labs run fine.
Will need fabletools 0.1.2 for fixes to `features()`.
